version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: video-accent-server
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
    ports:
      - '8000:8000'
    depends_on:
      - redis
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: video-accent-client
    env_file:
      - ./client/.env.local
    volumes:
      - ./client:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - backend
  redis:
    image: redis:6-alpine
    container_name: video-accent-redis
    ports:
      - '6379:6379'